### ISSUE TITLE
Code running problem

### ISSUE THREAD

**Issue by HZPHYT666** [XingBowen714/KaGRMN-DSG_ABSA#1]
![image](https://user-images.githubusercontent.com/55630111/158973401-738b85d9-9bb0-4b28-8d14-843031aadd05.png)
Hello, the code you provided can not run successfully, the tokenizer is missing, and there is no a n_gcn in args and tokenizer is no  in args

**Comment by XingBowen714** [comment]
Hi, I fixed some bugs, while I didn't encounter the `tokenize` error. Now the updated code can successfully work on my machine. You can try again it.
